#!/bin/bash

sandbox::config() {
  local typ=$1
  local version=latest
  if [ -z "$typ" ]; then
    log::error "type is required"
    exit 1
  fi

  # sandbox::run nodejs:v12 "npm run build"
  # here nodejs use v12
  if [ "$(string::has : $typ)" = "true" ]; then
    version=$(echo $type | awk -F ":" '{print $2}')
  fi

  local command="placeholder"
  local sandbox_dir="$PLUGIN_SANDBOX_SANDBOXS_DIR/$typ"
  if [ ! -d "$sandbox_dir" ]; then
    log::error "[sandbox::config] unsupport sandbox ($typ)"
    exit 1
  fi

  sandbox::load "$typ" "$command"
  
  cd $PLUGIN_SANDBOX_COMPOSE_DIR
  $DOCKER_COMPOSE config
}

export -f sandbox::config
