#!/bin/bash

sandbox::config() {
  local typ=$1
  if [ -z "$typ" ]; then
    log::error "type is required"
    exit 1
  fi

  local command="placeholder"
  local sandbox_dir="$PLUGIN_SANDBOX_SANDBOXS_DIR/$typ"
  if [ ! -d "$sandbox_dir" ]; then
    log::error "[sandbox::config] unsupport sandbox ($typ)"
    exit 1
  fi

  sandbox::load "$typ" "$command"
  
  cd $PLUGIN_SANDBOX_COMPOSE_DIR
  $DOCKER_COMPOSE config
}

export -f sandbox::config
