#!/bin/bash

sandbox::config() {
  local typ=$1
  local command=$2
  if [ -z "$typ" ]; then
    log::error "type is required"
    exit 1
  fi

  if [ -z "$command" ]; then
    log::error "command is required"
    exit 1
  fi

  local sandbox_dir="$PLUGIN_SANDBOX_SANDBOXS_DIR/$typ"
  if [ ! -d "$sandbox_dir" ]; then
    log::error "[sandbox::config] unsupport sandbox ($typ)"
  fi

  sandbox::load "$typ" "$command"
  
  cd $PLUGIN_SANDBOX_COMPOSE_DIR
  $DOCKER_COMPOSE config
}

export -f sandbox::config
