#!/bin/bash

sandbox::load() {
  local typ=$1
  local sandbox_config=$sandbox_dir/config
  cd $sandbox_dir

  if [ -f "$sandbox_config" ]; then
    config::load_file $sandbox_config
  fi

  export PLUGIN_SANDBOX_COMMAND=${command:-$PLUGIN_SANDBOX_COMMAND}
  export PLUGIN_SANDBOX_RUNNER_ID=$(os::uuid)
  export PLUGIN_SANDBOX_RUNNER_CONTAINER="sandbox_${typ}_${PLUGIN_SANDBOX_RUNNER_ID}"
}

export -f sandbox::load
