#!/bin/bash

sandbox::run() {
  local typ=$1
  local version=latest
  local command=$2
  local args=$3
  if [ -z "$typ" ]; then
    log::error "type is required"
    exit 1
  fi

  if [ -z "$command" ]; then
    # log::error "command is required"
    # exit 1
    command="sh"
  fi

  # sandbox::run nodejs:v12 "npm run build"
  # here nodejs use v12
  if [ "$(string::has : $typ)" = "true" ]; then
    version=$(echo $typ | awk -F ":" '{print $2}')
    typ=$(echo $typ | awk -F ":" '{print $1}')
  fi

  local sandbox_dir="$PLUGIN_SANDBOX_SANDBOXS_DIR/$typ"
  if [ ! -d "$sandbox_dir" ]; then
    log::error "[sandbox::run] unsupport sandbox ($typ)"
    exit 1
  fi

  sandbox::load "$typ" "$version" "$command"
  if [ "$?" != "0" ]; then
    log::error  "[$(timestamp)] failed to run in sandbox."
    return 1
  fi

  # sandbox::prepare "$typ"

  cd $PLUGIN_SANDBOX_COMPOSE_DIR

  # log::debug "run => $DOCKER_COMPOSE run app \"$command\""
  # $DOCKER_COMPOSE run app "$command"

  local tmp_error=$(os::tmp_file)
  if [ -f "$PLUGIN_SANDBOX_CONTEXT/$PLUGIN_SANDBOX_DOCKERFILE_NAME" ]; then
    export PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME=$PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME_FOR_DOCKERFILE
  fi

  if [ -n "$DEBUG" ]; then
    $DOCKER_COMPOSE -f $PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME config
  fi

  if [ "$PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME" != "" ]; then
    # need build
    log::info "[$(timestamp)] building fresh ..."
    $DOCKER_COMPOSE -f $PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME build 2>$tmp_error
    if [ "$?" != "0" ]; then
      log::error "[$(timestamp)] failed to build sandbox: $PLUGIN_SANDBOX_RUNNER_CONTAINER"
      cat $tmp_error
      return 1
    fi
  fi

  $DOCKER_COMPOSE -f $PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME up -d >>/dev/null 2>$tmp_error
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)] failed to start sandbox: $PLUGIN_SANDBOX_RUNNER_CONTAINER"
    cat $tmp_error
    return 1
  fi

  $DOCKER_COMPOSE -f $PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME exec app "$command"

  $DOCKER_COMPOSE -f $PLUGIN_SANDBOX_DOCKER_COMPOSE_FILE_NAME down
}

export -f sandbox::run
