#!/bin/bash

export PLUGIN_SANDBOX_NAME=go

export PLUGIN_SANDBOX_IMAGE_NAME=whatwewant/builder-go
export PLUGIN_SANDBOX_IMAGE_VERSION=v1.20-1

if [ -n "$GO_VERSION" ]; then
  GO_VERSION=${GO_VERSION#v}
fi

if [ "$GO_VERSION" = "1.19" ]; then
  export PLUGIN_SANDBOX_IMAGE_VERSION=v1.19-1
else if [ "$GO_VERSION" = "1.18" ]; then
  export PLUGIN_SANDBOX_IMAGE_VERSION=v1.18-1
fi
