version: '3.7'

services:
  app:
    image: ${PLUGIN_SANDBOX_IMAGE}
    working_dir: /src
    command: ${PLUGIN_SANDBOX_COMMAND}
    volumes:
      - ${PLUGIN_SANDBOX_CONTEXT}:/src

networks:
  default:
    external: true
    name: compose-ingress
