version: '3.7'

services:
  app:
    image: ${PLUGIN_SANDBOX_IMAGE}
    container_name: ${PLUGIN_SANDBOX_RUNNER_CONTAINER}
    working_dir: ${PLUGIN_SANDBOX_WORKDIR}
    environment:
      SANDBOX_CORE_NAME: ${PLUGIN_NAME}
      SANDBOX_CORE_VERSION: ${PLUGIN_VERSION}
      SANDBOX_CORE_DESCRIPTION: ${PLUGIN_DESCRIPTION}
      SANDBOX_RUNNER_NAME: ${PLUGIN_SANDBOX_NAME}
      SANDBOX_RUNNER_IMAGE: ${PLUGIN_SANDBOX_IMAGE}
      SANDBOX_RUNNER_CONTEXT: ${PLUGIN_SANDBOX_CONTEXT}
      SANDBOX_RUNNER_WORKDIR: ${PLUGIN_SANDBOX_WORKDIR}
      SANDBOX_RUNNER_COMMAND: ${PLUGIN_SANDBOX_COMMAND}
      SANDBOX_RUNNER_ID: ${PLUGIN_SANDBOX_RUNNER_ID}
      SANDBOX_RUNNER_CONTAINER: ${PLUGIN_SANDBOX_RUNNER_CONTAINER}
    command: ${PLUGIN_SANDBOX_COMMAND}
    volumes:
      - ${PLUGIN_SANDBOX_CONTEXT}:${PLUGIN_SANDBOX_WORKDIR}

networks:
  default:
    external: true
    name: compose-ingress
